apiVersion: v1
kind: PersistentVolume #PV(영구 볼륨)
metadata:
  name: host-pv
spec:
  capacity: #용량
    storage: 1Gi
  volumeMode: Filesystem #Filesystem,Block 두 가지가 있음
  storageClassName: standard #kubectl get sc를 하면 나옴. 그걸 사용한다는 뜻
  accessModes:
    - ReadWriteOnce #하나의 노드에서 해당 볼륨이 읽기-쓰기로 마운트될 수 있다.
  # - ReadOnlyMany 볼륨이 다수의 노드에서 읽기 전용으로 마운트될 수 있다.
  # - ReadWriteMany 볼륨이 다수의 노드에서 읽기-쓰기로 마운트될 수 있다.
  # - ReadWriteOncePod 볼륨이 단일 파드에서 읽기-쓰기로 마운트될 수 있다.
  hostPath:
    path: /data
    type: DirectoryOrCreate
