apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: host-pvc
spec:
  volumeName: host-pv #사용할 pv의 이름을 사용.
  accessModes:
    - ReadWriteOnce
  storageClassName: standard #kubectl get sc를 하면 나옴. 그걸 사용한다는 뜻
  resources:
    requests:
      storage: 1Gi
